# Generated by Django 5.2.16 on 2026-07-19 18:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=150)),
                ("display_name", models.CharField(blank=True, max_length=150)),
                ("profile_picture_url", models.URLField(blank=True, null=True)),
                (
                    "name_display_pref",
                    models.CharField(
                        choices=[
                            ("full_name", "Full name"),
                            ("display_name", "Display name"),
                        ],
                        default="full_name",
                        max_length=20,
                    ),
                ),
                ("last_name_change", models.DateTimeField(blank=True, null=True)),
                ("last_picture_change", models.DateTimeField(blank=True, null=True)),
                ("newsletter_opt_in", models.BooleanField(default=False)),
                ("tos_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("age_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("email_verified", models.BooleanField(default=False)),
                ("disable_live_notifications", models.BooleanField(default=False)),
                ("disable_away_notifications", models.BooleanField(default=False)),
                ("disable_all_notifications", models.BooleanField(default=False)),
                (
                    "last_seen_rank",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("bronze", "Bronze"),
                            ("unranked", "Unranked"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("notified_gold", models.BooleanField(default=False)),
                ("notified_top3", models.BooleanField(default=False)),
                ("moderation_reset_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
    ]
