# Generated by Django 5.2.16 on 2026-07-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_full_name_change",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
