# Generated by Django 5.2.16 on 2026-07-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_last_full_name_change"),
    ]

    operations = [
        migrations.CreateModel(
            name="TosVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="tos_accepted_version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
