# Generated by Django 5.2.16 on 2026-07-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="display_consent",
        ),
    ]
